name: checker
on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "docs/**"
      - "www"
      - "README.md"

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

  check:
    runs-on: ubuntu-latest
    needs: [cancel]
    steps:
      - uses: actions/checkout@v2

      - name: compose up
        run: make dc-unittest -C tests

      - name: lint
        run: docker compose -f ./tests/docker/docker-compose.yml exec unittest make lint

      - name: make
        run: docker compose -f ./tests/docker/docker-compose.yml exec unittest make re

      - name: unittest
        run: docker compose -f ./tests/docker/docker-compose.yml exec unittest make unit
