name: checker
on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "docs/**"
      - "www"
      - "README.md"

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

  check:
    runs-on: ubuntu-latest
    needs: [cancel]
    steps:
      - uses: actions/checkout@v2

      - name: setup
        shell: bash
        run: |
          sudo apt-get install -y \
            cmake \
            make \
            gcc \
            googletest \
            g++ \
            python3-pip \
            valgrind \
            clang-format \
            clang-tidy && \
          pip install cpplint && \
            (cd /usr/src/googletest && pwd && cmake . && echo 'hoge' && cmake --build . --target install)

      - name: lint
        shell: bash
        run: make lint -C tests

      - name: unit test
        shell: bash
        run: make unittest -C tests
