name: checker
on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "docs/**"
      - "www"
      - "README.md"

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

  check:
    runs-on: ubuntu-latest
    needs: [cancel]
    steps:
      - uses: actions/checkout@v2
      - name: compose-build
        shell: bash
        run: make dc-build
      - name: compose up
        shell: bash
        run: make dc-up
      - name: lint
        shell: bash
        run: docker compose -f ./docker/webserv/docker-compose.yaml exec -T webserv make lint
      - name: make
        shell: bash
        run: docker compose -f ./docker/webserv/docker-compose.yaml exec -T webserv make re
      - name: unittest
        shell: bash
        run: docker compose -f ./docker/webserv/docker-compose.yaml exec -T webserv make unit
